spring:
  data:
    redis:
      host: localhost
      port: 9091
      password: 123456
  mail:
    host: smtp.163.com
    username: tzltangzilong2023@163.com
    password: LHfPfmw3SryQ2X6q
  rabbitmq:
    addresses: 192.168.190.128
    username: admin
    password: admin
    virtual-host: /test
  security:
    filter:
      order: -100
    jwt:
      key: asdfasdf
      expire: 7
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project1
